esphome:
  name: garage-door
  # Added below to improve staying connected
  on_boot:
    priority: 300
    then:
      lambda: |-
        WiFi.setPhyMode(WIFI_PHY_MODE_11G);

esp8266:
  board: esp01_1m
  framework:
    version: recommended

substitutions:
  friendly_name: Garage Door

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "{YOUR_KEY}" # Insert your Home Asistant Encrption Key here
  reboot_timeout: 10min

ota:
  - platform: esphome
    password: "{YOUR_PWD}" # Insert your Home Asistant esphome OTA password here

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: !secret admin_password
  # Static values also seem to help it stay connected
  manual_ip:
    static_ip: 192.168.x.x
    gateway: 192.168.x.x
    subnet: 255.255.255.0
    dns1: 1.1.1.1 # Change for your preferred DNS
    dns2: 1.0.0.1
  power_save_mode: none
  reboot_timeout: 60min

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret admin_user
    password: !secret admin_password

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/London

# Send WiFi signal strength & uptime to HA
sensor:
  - platform: wifi_signal
    name: $friendly_name WiFi Strength
    update_interval: 60s
  - platform: uptime
    name: $friendly_name "Uptime"

# The door contact sensor that is attached to SW on the Shelly 1. Not exposed to HA, instead used to set the state of the cover.
binary_sensor:
  - platform: gpio
    pin: GPIO3
    name: "Garage Door Contact Sensor"
    id: contact_sensor
    device_class: garage_door
#    internal: true # hides sensor from HA
    filters:
      - delayed_off: 500ms # Stops sensor bouncing (open-closed)

# Send IP Address to HA
text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
    ssid:
      name: $friendly_name Connected SSID

# This creates the actual garage door in HA. The state is based on the contact sensor. Opening/closing the garage door simply turns the relay on/off with a 0.5s delay in between.
cover:
  - platform: template
    device_class: garage
    name: "Garage Door"
    id: template_cov
    lambda: |-
      if (id(contact_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
    close_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
    stop_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay

# The relay in the Shelly 1 that will deliver the pulse to the garage door opener (not exposed to HA)
switch:
  - platform: gpio
    pin: GPIO4
    name: "Garage Door Relay"
    id: relay
    internal: true

# Restart button
button:
  - platform: restart
    name: $friendly_name "Reboot"